let newSet = new Set()
newSet.add("Elmar")
newSet.add("raul")
newSet.add("vahid")
console.log(newSet)
console.log(newSet.size)
console.log(newSet.has("Elmar"))
console.log(newSet.delete("vahid"))
console.log(newSet.size)
console.log(newSet.values("raul"))